homepage:
    pattern: /
    defaults: { _controller: ReservableActivityBundle:Default:homepage }
    requirements:
            _method:  GET

new_activity:
    path: /new-property
    defaults: { _controller: ReservableActivityBundle:Registration:new }

new_features:
    path: /new-features
    defaults: { _controller: ReservableActivityBundle:Registration:newFeature }

delete_features:
    path: /delete-feature
    defaults: { _controller: ReservableActivityBundle:Admin:deleteFeature }
    requirements:
        _method:  GET|POST
    options:
        expose: true

add_features:
    path: /add-feature
    defaults: { _controller: ReservableActivityBundle:Admin:addFeature }
    requirements:
        _method:  GET|POST
    options:
        expose: true

admin_types:
    path: /admin-types
    defaults: { _controller: ReservableActivityBundle:Registration:adminTypes }

delete_type:
    path: /delete-type
    defaults: { _controller: ReservableActivityBundle:Admin:deleteType }
    requirements:
        _method:  GET|POST
    options:
        expose: true

modify_type:
    path: /modify-type
    defaults: { _controller: ReservableActivityBundle:Admin:modifyType }
    requirements:
        _method:  GET|POST
    options:
        expose: true

add_type:
    path: /add_type
    defaults: { _controller: ReservableActivityBundle:Admin:addType }
    requirements:
        _method:  GET|POST
    options:
        expose: true

admin_features:
    path: /admin-features
    defaults: { _controller: ReservableActivityBundle:Registration:adminFeatures }

register_activity:
    path: /register-property
    defaults: { _controller: ReservableActivityBundle:Registration:registerActivity }

activityRegistered:
    path: /property-registered
    defaults: { _controller: ReservableActivityBundle:Registration:registeredActivity }

view_activities:
    path: /admin/view-properties
    defaults: { _controller: ReservableActivityBundle:View:view }

modify_property:
    path: /modify-property
    defaults: { _controller: ReservableActivityBundle:View:modifyProperty }

active_property:
    path: /active-property
    defaults: { _controller: ReservableActivityBundle:View:activeProperty }

deactive_property:
    path: /deactive-property
    defaults: { _controller: ReservableActivityBundle:View:deactiveProperty }

delete_property:
    path: /delete-property
    defaults: { _controller: ReservableActivityBundle:View:deleteProperty }

search:
    path: /search
    defaults: { _controller: ReservableActivityBundle:Searcher:search }

uploadPicture:
    path: /upload-picture
    defaults: { _controller: ReservableActivityBundle:Picture:uploadFile }

registerPicture:
    path: /register-picture
    defaults: { _controller: ReservableActivityBundle:Picture:registerPicture }

details:
    path: /view-details/{property}
    defaults: { _controller: ReservableActivityBundle:View:viewDetails }

adminDetails:
    path: /admin/view-details/{property}
    defaults: { _controller: ReservableActivityBundle:Admin:viewDetails }

adminDetailsModif:
    path: /admin/view-details/{property}/modif
    defaults: { _controller: ReservableActivityBundle:Admin:modifDetails }

activeModif:
    path: /admin/view-details/{property}/active
    defaults: { _controller: ReservableActivityBundle:Admin:modifActive }

deleteModif:
    path: /admin/view-details/{property}/delete
    defaults: { _controller: ReservableActivityBundle:Admin:modifDelete }

deactiveModif:
    path: /admin/view-details/{property}/deactive
    defaults: { _controller: ReservableActivityBundle:Admin:modifDeactive }

modifDetailsProperty:
    path: /admin/view-details/{property}/modif/save
    defaults: { _controller: ReservableActivityBundle:Admin:saveModifDetails }

view_users:
    path: /view-users
    defaults: { _controller: UserUserBundle:Consult:viewUsers }

view_users_modif:
    path: /view-users/{userId}
    defaults: { _controller: UserUserBundle:Consult:viewUsersModif }

view_users_delete:
    path: /view-users/{userId}/delete
    defaults: { _controller: UserUserBundle:Consult:deleteUser }

checkUser:
    pattern: /checkUser
    defaults: { _controller: UserUserBundle:Consult:checkUser }
    requirements:
        _method:  GET|POST
    options:
        expose: true

loadImages:
    pattern: /loadImages
    defaults: { _controller: ReservableActivityBundle:Picture:loadImages }
    requirements:
        _method:  GET|POST
    options:
        expose: true
