hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /{_locale}/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /{_locale}/loginWithRRSS

google_login:
    pattern: /{_locale}/login/check-google

user_user:
    resource: "@UserUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

reservable_activity:
    resource: "@ReservableActivityBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/

bookings_booking:
    resource: "@BookingsBookingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/