## FosUserBundle Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/

## HWIOAuthBundle routes
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect


hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

facebook_login:
    pattern: /facebook

google_login:
    pattern: /google

## EasyAdminBundle
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/superUserAdmin

## My own bundles
admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

user_user:
    resource: "@UserUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

reservable_activity:
    resource: "@ReservableActivityBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

bookings_booking:
    resource: "@BookingsBookingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


