user_user:
    resource: "@UserUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

reservable_activity:
    resource: "@ReservableActivityBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/

bookings_booking:
    resource: "@BookingsBookingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
