security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        hwi:
            id: hwi_oauth.user.provider
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /es/consult-bookings
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true
        secured_area:
            oauth:
                resource_owners:
                    facebook:      /login_facebook
                    google:        /login_google
                login_path:        /es/consult-bookings
                failure_path:      /login
                oauth_user_provider:
                    service: my_user_provider
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider 

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/view-properties/, role: ROLE_USER }
        - { path: ^/es/view-users, role: ROLE_USER }
        - { path: ^/es/new-property, role: ROLE_USER }
        - { path: ^/es/consult-bookings, role: ROLE_USER }
        - { path: ^/es/calendar, role: ROLE_USER }
        - { path: ^/es/history-bookings, role: ROLE_USER }
        - { path: ^/es/admin-types, role: ROLE_ADMIN }
        - { path: ^/es/admin-features, role: ROLE_ADMIN }
        - { path: ^/es/new-features, role: ROLE_ADMIN }
        - { path: ^/es/admin-zones, role: ROLE_ADMIN }
        - { path: ^/es/statistics, role: ROLE_USER }
        - { path: ^/en/view-users, role: ROLE_USER }
        - { path: ^/en/new-property, role: ROLE_USER }
        - { path: ^/en/consult-bookings, role: ROLE_USER }
        - { path: ^/en/calendar, role: ROLE_USER }
        - { path: ^/en/history-bookings, role: ROLE_USER }
        - { path: ^/en/admin-types, role: ROLE_ADMIN }
        - { path: ^/en/admin-features, role: ROLE_ADMIN }
        - { path: ^/en/new-features, role: ROLE_ADMIN }
        - { path: ^/en/admin-zones, role: ROLE_ADMIN }
        - { path: ^/en/statistics, role: ROLE_USER }
        - { path: ^/en/book/, role: ROLE_USER }
        - { path: ^/es/book/, role: ROLE_USER }
        - { path: ^/es/make-rating, role: ROLE_USER }
        - { path: ^/en/make-rating, role: ROLE_USER }
