<?php

namespace Reservable\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityyToTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityyToTypeRepository extends EntityRepository
{
    public function getTypeSelected($propertyID){
        $type =  $this->getEntityManager()
            ->createQuery("SELECT t.typeID
                		   FROM ReservableActivityBundle:ActivityyToType t
                		   WHERE t.activityID = " . $propertyID)
            ->getResult();

        return ($type) ? $type[0]['typeID'] : false ;
    }
}
