<?php

namespace Reservable\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityToFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityToFeatureRepository extends EntityRepository
{


    public function getAllFeatures($propertyID){
        $features =  $this->getEntityManager()
            ->createQuery("SELECT f.featureID
                		   FROM ReservableActivityBundle:ActivityToFeature f
                		   WHERE f.activityID = " . $propertyID)
            ->getResult();

        $result = array();
        foreach($features as $oneFeature){
            $result[] = $oneFeature['featureID'];
        }

        return $result;
    }


}
