<?php

namespace Reservable\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityToIcalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityToIcalRepository extends EntityRepository
{

    function getAllIcsFromActivityFormatted($activityID)
    {
        $return = '';

        $icals = $this->getEntityManager()
            ->createQuery('SELECT ati.id, ati.icalUrl
                           FROM ReservableActivityBundle:ActivityToIcal ati
                           WHERE ati.id = ' . $activityID)
            ->getResult();

        if(!empty($icals)){
            foreach($icals as $ical) {

                $namesPart  = explode('/', $ical['icalUrl']);
                $name       = $namesPart[2];

                $return .= "<div class='row' id='ical-" . $ical['id'] . "'><div class='col-md-8'></div><div class='col-md-2 text-center nameIcal' title='" . $ical['icalUrl'] . "'>" . $name . "</div><div class='col-md-1 text-right deleteIcal' icalID='" . $ical['id'] . "'><i class='fa fa-trash-o'></i></div><div class='col-md-1 text-left refreshIcal' icalID='" . $ical['id'] . "'><i class='fa fa-refresh'></i></div></div>";
            }
        }

        return $return;
    }

}
