<?php

namespace Reservable\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturesRepository extends EntityRepository
{

    public function getAllFeatures(){
        $features = $this->getEntityManager()
            ->createQuery("SELECT f.id, f.name FROM ReservableActivityBundle:Features f")
            ->getResult();

        return $features;
    }

    public function getIdByName($name){
        $types = $this->getEntityManager()
            ->createQuery("SELECT t.id
                		   FROM ReservableActivityBundle:Features t
                		   WHERE t.name LIKE '" . $name . "'")
            ->getResult();

        return ($types[0])?$types[0]:false;
    }
}
