<?php

namespace Reservable\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturesRepository extends EntityRepository
{

    public function getAllFeatures(){
        $features = $this->getEntityManager()
            ->createQuery("SELECT f.id, f.name FROM ReservableActivityBundle:Features f")
            ->getResult();

        return $features;
    }
}
