<?php

namespace Reservable\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository
{
	function findAllIn($picturesIDs){
		
		return $this->getEntityManager()
            		->createQuery('SELECT p 
                				   FROM ReservableActivityBundle:Picture p
                				   WHERE p.activityID IN (' . $picturesIDs . ')')
            		->getResult();
	}
}
