<?php

namespace Bookings\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
	function findBookingsFromPropertyID($propertyID){
		return $this->getEntityManager()
            	    ->createQuery('SELECT b
            	   				   FROM BookingsBookingBundle:Booking b
                				   WHERE b.activityID = ' . $propertyID)
            		->getResult();
	}

	function getLastBookingID(){
		return $this->getEntityManager()
            	    ->createQuery('SELECT MAX(b.id)
            	   				   FROM BookingsBookingBundle:Booking b')
            		->getResult();
	}
}
