book:
    path:     /book/
    defaults: { _controller: BookingsBookingBundle:Default:book }

confirmBooking:
    path:     /booking-confirmed/
    defaults: { _controller: BookingsBookingBundle:Default:confirmBooking }

consultBookings:
    path:     /consult-bookings/
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:consultBookings }

consultClientBookings:
    path:     /consult-client-bookings/
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:consultclientBookings }

historyBookings:
    path:     /history-bookings/
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:historyBookings }

historyBookingsUser:
    path:     /history-bookings-user/
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:historyBookingsUser }

calendarBookings:
    path:     /calendar/
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:calendarBookings }

acceptBooking:
    path:     /accept-booking/
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:acceptBooking }

cancelBooking:
    path:     /cancel-booking/
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:cancelBooking }

calculateCalendar:
    pattern: /calculateCalendar
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:calculateCalendar }
    requirements:
        _method:  GET|POST
    options:
        expose: true

importCalendarFromURI:
    pattern: /importCalendarFromURI
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:importCalendarFromURI }
    requirements:
        _method:  GET|POST
    options:
        expose: true

refreshIcal:
    pattern: /refreshIcal
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:refreshIcal }
    requirements:
        _method:  GET|POST
    options:
        expose: true

deleteIcal:
    pattern: /deleteIcal
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:deleteIcal }
    requirements:
        _method:  GET|POST
    options:
        expose: true

delete_reserve:
    path: /delete_reserve
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:deleteReserve }
    requirements:
        _method:  GET|POST
    options:
        expose: true