book:
    path:     /book/
    defaults: { _controller: BookingsBookingBundle:Default:book }

confirmBooking:
    path:     /booking-confirmed/
    defaults: { _controller: BookingsBookingBundle:Default:confirmBooking }

consultBookings:
    path:     /consult-bookings/
    defaults: { _controller: BookingsBookingBundle:ConsultBookings:consultBookings }