parameters:
#    ragings_rating.example.class: Ragings\RatingBundle\Example

services:
#    ragings_rating.example:
#        class: %ragings_rating.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
