<?php

namespace User\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
	function getUserByUserID($userID){

		$user = new Users();

		$result = $this->getEntityManager()
                    ->createQuery('SELECT u
                                  FROM UserUserBundle:Users u
                                  WHERE u.id = ' . $userID)
                    ->getResult();

        if($result[0]) $user = $result[0];

        return $user;
	}
}
